model_name: multi_depth

# Multi unsupervised depth model config
levels: [0, 1, 2, 3]
depth_down_sample: net
inner_lambda_s: 0.5
detach: True

# Optimizer configs
lr: 0.0001
beta1: 0.9
beta2: 0.99

# Data model
batch_size: 2
num_workers: 4
split: [0.8, 0.1, 0.1]
image_size: [128, 384]
transform_filters: True
